export const serverEnv = {
  DATABASE_URL: process.env.DATABASE_URL ?? "",
  NODE_ENV: process.env.NODE_ENV ?? "development",
  isProduction: process.env.NODE_ENV === "production",
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL ?? "",
  NEXT_PUBLIC_GA_MEASUREMENT_ID: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID ?? "",
  NEXT_PUBLIC_GTM_ID: process.env.NEXT_PUBLIC_GTM_ID ?? "",
  GOOGLE_SITE_VERIFICATION: process.env.GOOGLE_SITE_VERIFICATION ?? "",
  ADMIN_NOTIFICATION_EMAIL: process.env.ADMIN_NOTIFICATION_EMAIL ?? "",
  MAIL_FROM: process.env.MAIL_FROM ?? "",
  SMTP_HOST: process.env.SMTP_HOST ?? "",
  SMTP_PORT: process.env.SMTP_PORT ?? "",
  SMTP_USER: process.env.SMTP_USER ?? "",
  SMTP_PASS: process.env.SMTP_PASS ?? "",
  SMTP_SECURE: process.env.SMTP_SECURE ?? "false",
  INQUIRY_RATE_LIMIT_MAX: process.env.INQUIRY_RATE_LIMIT_MAX ?? "5",
  INQUIRY_RATE_LIMIT_WINDOW_MS: process.env.INQUIRY_RATE_LIMIT_WINDOW_MS ?? "900000",
  INQUIRY_MIN_SUBMIT_MS: process.env.INQUIRY_MIN_SUBMIT_MS ?? "1500",
  ADMIN_EMAIL: process.env.ADMIN_EMAIL ?? "",
  ADMIN_PASSWORD: process.env.ADMIN_PASSWORD ?? "",
  ADMIN_SESSION_SECRET: process.env.ADMIN_SESSION_SECRET ?? "",
  ADMIN_UPLOAD_MAX_IMAGE_BYTES: process.env.ADMIN_UPLOAD_MAX_IMAGE_BYTES ?? "3145728",
  REDIS_URL: process.env.REDIS_URL ?? "",
  REDIS_PREFIX: process.env.REDIS_PREFIX ?? "remember-everything:",
} as const;
